import Head from "next/head";
import { Inter } from "next/font/google";
import Title from "@/components/title";
import DragSection from "@/components/DragSection/Index";
import { DndProvider } from "react-dnd";
import { HTML5Backend } from "react-dnd-html5-backend";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const kpiOptions = [
        "Total Cases",
        "Total Open Cases",
        "Total Questions",
        "Total Open Questions",
    ];

    const chartOptions = [];
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <DndProvider backend={HTML5Backend}>
                <main>
                    <Title />
                    <DragSection kpiOptions={kpiOptions} />
                </main>
            </DndProvider>
        </>
    );
}
