import Head from "next/head";
import { Inter } from "next/font/google";

import Title from "@/components/title";
import DragSection from "@/components/DragSection/Index";
import DndBoard from "@/components/DashboardBuilder/Index";
import DashboardBuilder from "@/components/DashboardBuilder/Index";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const kpiOptions = [
        "Total Cases",
        "Total Open Cases",
        "Total Questions",
        "Total Open Questions",
    ];
    const chartOptions = [
        "Questions Over Time",
        "Questions by Turnaround Time",
        "Questions by Topic",
        "Questions by Status",
    ];

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Title />
                {/* <DragSection
                    kpiOptions={kpiOptions}
                    chartOptions={chartOptions}
                /> */}
                <DashboardBuilder />
            </main>
        </>
    );
}
